<?php
    $groupValue = $block->getGalleryData();
    $groupListValue = $block->getGroupListData();
?>

<script>
    var ul_one_playlist = document.getElementById("nav-playlist");
    require([
        'jquery'
    ], function ($) {
        'use strict';
        var htmlOneVideo =
            '<div class="link_one_video">' +
            '   <span class= "thumbnail-one-video">' +
            '       <div class="video11" style ="height:96px;width:126px">' +
            '           <img class = "one-video-thumbnail" style="height:96px" src="">' +
            '           </img>' +
            '       </div>' +
            '   </span>' +
            '   <span id ="play"></span>' +
            '</div>' +
            '<div class="info-one-video">' +
            '   <div><a class = "title-one-video-url" href =""></a></div>' +
            '   <div class ="time-publish-one-video" ></div>' +
            '</div>';


        function getPopup(oneID, modal) {
            $.get('https://www.googleapis.com/youtube/v3/videos?id=' + oneID + '&key=AIzaSyBeY89QEyaa5z3O1Gtyc4vI6XKBzftsTJE&part=statistics,snippet,contentDetails,status,player,recordingDetails',
                null,
                function (response) {
                    var data = response;
                    var videoTitle = data['items'][0]['snippet']['title'];
                    var videoChannelTitle = data['items'][0]['snippet']['channelTitle'];
                    var videoChannelId = data['items'][0]['snippet']['channelId'];
                    var videoThumbnail = data['items'][0]['snippet']['thumbnails']['default']['url'];
                    var videoPublishedAt = data['items'][0]['snippet']['publishedAt'];
                    var videoDescription = data['items'][0]['snippet']['description'];
                    var videoViews = data['items'][0]['statistics']['viewCount'];
                    var videoLikes = data['items'][0]['statistics']['likeCount'];
                    var videoDislikes = data['items'][0]['statistics']['dislikeCount'];
                    $(modal).children('.video-content').children().attr("src", "https://www.youtube.com/embed/" + oneID + "?enablejsapi=1&autoplay=false&showinfo=false");
                    $(modal).children('.popup-content').children('.watch-headline').children().text(videoTitle);
                    $(modal).children('.popup-content').children('.watch-video-info-meta').children('.watch-video-channel').children('.watch-thumbnail-channel').children().attr("herf", "https://www.youtube.com/channel/" + videoChannelId + "");
                    $(modal).children('.popup-content').children('.watch-video-info-meta').children('.watch-video-channel').children('.watch-thumbnail-channel').children().children().attr("src", videoThumbnail);
                    $(modal).children('.popup-content').children('.watch-video-info-meta').children('.watch-video-channel').children('.watch-video-channel-info').children('.watch-video-channel-info-name').attr("href", "https://www.youtube.com/channel/" + videoChannelId + "");
                    $(modal).children('.popup-content').children('.watch-video-info-meta').children('.watch-video-channel').children('.watch-video-channel-info').children('.watch-video-channel-info-name').text(videoChannelTitle);
                    $(modal).children('.popup-content').children('.watch-video-info-meta').children('.watch-video-properties').children('.watch-video-views').text(videoViews);
                    $(modal).children('.popup-content').children('.watch-video-info-meta').children('.watch-video-properties').children('.watch-video-rating').children('.watch-video-rating-count').children('.watch-video-like').children('.watch-video-likes').text(videoLikes);
                    $(modal).children('.popup-content').children('.watch-video-info-meta').children('.watch-video-properties').children('.watch-video-rating').children('.watch-video-rating-count').children('.watch-video-dislike').children('.watch-video-dislikes').text(videoDislikes);
                    $(modal).children('.popup-content').children('.watch-video-info-main').children('.watch-video-publish-date').text(videoPublishedAt);
                    $(modal).children('.popup-content').children('.watch-video-info-main').children('.watch-video-description').text(videoDescription);
                    $.get('https://www.googleapis.com/youtube/v3/channels?part=snippet&id=' + videoChannelId + '&key=AIzaSyBeY89QEyaa5z3O1Gtyc4vI6XKBzftsTJE',
                        null,
                        function (response) {
                            var data = response;
                            var profileImageUrl = data['items'][0]['snippet']['thumbnails']['default']['url'];
                            $('#watch-thumbnail-channel-img').attr("src", profileImageUrl);
                        });
                });
        }

        function getPopupCmt(oneID) {
            $.get('https://www.googleapis.com/youtube/v3/commentThreads?key=AIzaSyBeY89QEyaa5z3O1Gtyc4vI6XKBzftsTJE&textFormat=plainText&part=snippet&videoId=' + oneID + '&maxResults=5',
                null,
                function (response) {
                    var data = response;
                    var itemtCount = data['items'];
                    var divCmtParent = document.getElementById('watch-video-cmts');
                    $.each(itemtCount, function (keyCmt) {
                        var authorDisplayName = data['items'][keyCmt]['snippet']['topLevelComment']['snippet']['authorDisplayName'];
                        var authorProfileImage = data['items'][keyCmt]['snippet']['topLevelComment']['snippet']['authorProfileImageUrl'];
                        var authorChannel = data['items'][keyCmt]['snippet']['topLevelComment']['snippet']['authorChannelUrl'];
                        var textDisplay = data['items'][keyCmt]['snippet']['topLevelComment']['snippet']['textDisplay'];
                        var updateCmt = data['items'][keyCmt]['snippet']['topLevelComment']['snippet']['updatedAt'];
                        var divCmt = document.createElement('div');
                        divCmt.setAttribute('class', 'watch-video-cmts-item');
                        var divChildCmt1 = document.createElement('div');
                        divChildCmt1.setAttribute('class', 'watch-video-cmts-item-profile')
                        divCmt.appendChild(divChildCmt1);
                        var divChildCmt1a = document.createElement('a');
                        divChildCmt1a.setAttribute('class', 'watch-video-cmts-item-profile-img-url');
                        divChildCmt1a.setAttribute('href', authorChannel);
                        divChildCmt1.appendChild(divChildCmt1a);
                        var divChildCmt1aimg = document.createElement('img');
                        divChildCmt1aimg.setAttribute('class', 'watch-video-cmts-item-profile-img');
                        divChildCmt1aimg.setAttribute('style', 'width:48px; height:48px');
                        divChildCmt1aimg.setAttribute('src', authorProfileImage);
                        divChildCmt1a.appendChild(divChildCmt1aimg);
                        var divChildCmt2 = document.createElement('div');
                        divChildCmt2.setAttribute('class', 'watch-video-cmts-item-info');
                        divCmt.appendChild(divChildCmt2);
                        var divChildCmt2Div = document.createElement('div');
                        divChildCmt2Div.setAttribute('class', 'watch-video-cmts-item-header');
                        divChildCmt2.appendChild(divChildCmt2Div);
                        var divChildCmt2DivDiv1 = document.createElement('div');
                        divChildCmt2DivDiv1.setAttribute('class', 'watch-video-cmts-item-name');
                        divChildCmt2Div.appendChild(divChildCmt2DivDiv1);
                        var divChildCmt2DivDiv1A = document.createElement('a');
                        divChildCmt2DivDiv1A.setAttribute('class', 'watch-video-cmts-item-name-url');
                        divChildCmt2DivDiv1A.setAttribute('href', authorChannel);
                        divChildCmt2DivDiv1.appendChild(divChildCmt2DivDiv1A)
                        var nameText = document.createTextNode(authorDisplayName);
                        divChildCmt2DivDiv1A.appendChild(nameText);
                        var divChildCmt2DivDiv2 = document.createElement('div');
                        divChildCmt2DivDiv2.setAttribute('class', 'watch-video-cmts-item-time');
                        divChildCmt2Div.appendChild(divChildCmt2DivDiv2);
                        var timeText = document.createTextNode(updateCmt);
                        divChildCmt2DivDiv2.appendChild(timeText);
                        var divChildCmt2Div2 = document.createElement('div');
                        divChildCmt2Div2.setAttribute('class', 'watch-video-cmts-item-text');
                        var cmtText = document.createTextNode(textDisplay);
                        divChildCmt2Div2.appendChild(cmtText);
                        divChildCmt2.appendChild(divChildCmt2Div2);
                        divCmtParent.appendChild(divCmt);
                    });
                });
        }
        function getInforVideo(code,divAddChild,pageToken){
            $.get('https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&maxResults=3&playlistId='+code+'&key=AIzaSyBeY89QEyaa5z3O1Gtyc4vI6XKBzftsTJE&pageToken='+pageToken+'',
                null,
                function getVideoPlayList(response) {
                    var data = response;
                    var listCount = data['items'];
                    $.each(listCount, function (key) {
                        var titleOneVideo = data['items'][key]['snippet']['title'];
                        var publishedOneAt = data['items'][key]['snippet']['publishedAt'];
                        var pubYYYYMMDD = publishedOneAt.substring(0, 10);
                        var thumbnailOne = data['items'][key]['snippet']['thumbnails']['default']['url'];
                        var videoOneId = data['items'][key]['snippet']['resourceId']['videoId'];
                        var divOneVideo = document.createElement('div');
                        divOneVideo.setAttribute("class", "one-video");
                        divOneVideo.setAttribute("id", videoOneId);
                        divOneVideo.innerHTML = htmlOneVideo;
                        divAddChild.appendChild(divOneVideo);
                        var replaceID = document.querySelectorAll('[id = "'+videoOneId+'"]');
                        $(replaceID).children(".link_one_video").children().children().children().attr("src", thumbnailOne);
                        $(replaceID).children(".info-one-video").children().children().attr("href", "https://www.youtube.com/watch?v=" + videoOneId + "");
                        $(replaceID).children(".info-one-video").children().children().text(titleOneVideo);
                        $(replaceID).children(".info-one-video").children(".time-publish-one-video").text(pubYYYYMMDD);
                        showPopup(videoOneId);
                    })
                })
        }

        function showPopup(videoOneId) {
            var btn = document.getElementById(videoOneId);
            var modal = document.getElementById('popup-page');
            btn.onclick = function() {
                modal.style.display = "block";
                var oneID1 = btn.getAttribute('id');
                getPopup(oneID1,modal);

                getPopupCmt (oneID1);

            };
        }



        function addID_show(id_one) {
            var divShow = document.createElement("div");
            var divAddChild = document.getElementById(id_one);
            divShow.setAttribute("id", "show-playlist-"+id_one+"");
            divAddChild.appendChild(divShow);
        }

        function addId_XX(id_gr, id_one){
            var divAdd = document.getElementById('gr_'+id_gr+'');
            var divAddChild = document.createElement('div');
            divAddChild.setAttribute("id",id_one);
            divAdd.appendChild(divAddChild);
        }

        function showPlaylist(code, id_gr, id_one, pageToken) {

            $.get('https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&maxResults=3&playlistId=' + code + '&key=AIzaSyBeY89QEyaa5z3O1Gtyc4vI6XKBzftsTJE&pageToken=' + pageToken + '',
                null,
                function (response) {
                    var data = response;
                    var checkk = data['items'];

                    if (checkk[0] == null || checkk[0] == "") {
                        alert("Your playlist is not exist");
                    }
                    else {
                        var nextToken = data['nextPageToken'];
                        var prevToken = data['prevPageToken'];
                        var divAdd = document.getElementById('gr_' + id_gr + '');
                        var countID = divAdd.childElementCount;
                        var i;
                        var checkID = 0;

                        for (i = 0; i < countID; i++) {
                            if ($(divAdd).children()[i].getAttribute("id") == id_one) {
                                checkID++;
                            }
                        }
                        if (checkID == 0) {
                            addId_XX(id_gr, id_one);
                        }
                        var countXX = document.getElementById(id_one).childElementCount;
                        if (countXX == 0) {
                            addID_show(id_one);
                            var divAddChild = $(divAdd).children("#" + id_one + "").children("#show-playlist-" + id_one + "")[0];
                            getInforVideo(code, divAddChild, "");
                        }
                        var nextPage = document.getElementById("nex-page");
                        nextPage.onclick = function () {
                            var countNext = divAdd.childElementCount - 1;

                            if (nextToken != null) {
                                showPlaylist(code, id_gr, countNext, nextToken);
                                $(divAdd).children("#" + countNext + "").show();
                                $(divAdd).children("#" + countNext + "").children().remove();
                                addID_show(id_one);
                                var divAddChild = $(divAdd).children("#" + countNext + "").children().eq(0)[0];
                                getInforVideo(code, divAddChild, nextToken);
                            }
                        };
                        var prevPage = document.getElementById("pre-page");
                        prevPage.onclick = function () {
                            if (prevToken != null) {
                                showPlaylist(code, id_gr, id_one, prevToken);
                                $(divAdd).children("#" + id_one + "").children().remove();
                                addID_show(id_one);
                                var divAddChild = $(divAdd).children("#" + id_one + "").children().eq(0)[0];
                                getInforVideo(code, divAddChild, prevToken);
                            }
                        }


                    }
                });
        }
        function getChannel(video_code) {
            $.get('https://www.googleapis.com/youtube/v3/channels?part=statistics,brandingSettings,snippet,contentDetails&id='+video_code+'&key=AIzaSyBeY89QEyaa5z3O1Gtyc4vI6XKBzftsTJE',
                null,
                function (response) {
                    var data = response;
                    var check = data['items'];
                    if(check[0] == null || check[0] == ""){
                        alert("Your Channel is not exist");
                    }
                    else {
                        var upLoadId = data['items'][0]['contentDetails']['relatedPlaylists']['uploads'];
                        var bannerImageUrl = data['items'][0]['brandingSettings']['image']['bannerImageUrl'];
                        var description = data['items'][0]['brandingSettings']['channel']['description'];
                        var title = data['items'][0]['brandingSettings']['channel']['title'];
                        var profileImageUrl = data['items'][0]['snippet']['thumbnails']['default']['url'];
                        $('#img-profile-channel').attr("src", profileImageUrl);
                        var style = "background-image: url('" + bannerImageUrl + "'); background-size: auto 100% ";
                        var url = "https://www.youtube.com/channel/" + video_code + "";
                        $('#banner').attr("style", style);
                        $('#video_title').attr("value", title);
                        $('#video_description').attr("value", description);
                        $('#title_h1').text(title);
                        $('.link_video').attr("href", url);
                        var des2 = $('#description').text(description);
                        $('#playlist-input-value-name').attr("value", "Upload Videos");
                        $('#playlist-input-value').attr("value", "https://www.youtube.com/playlist?list="+upLoadId);
                        $('#playlist-name').text("Upload Videos");
                        $('#li_0').children().text("Upload Videos");

                        var divAddd = document.getElementById('gr_0');
                        var liSpan = document.getElementById('li_0');
                        divAddd.classList.add("show-playlist-active");
                        liSpan.classList.add("show-name-playlist-active");
                        var videoCount = data['items'][0]['statistics']['videoCount'];
                        var subscriberCount = data['items'][0]['statistics']['subscriberCount'];
                        var viewCount = data['items'][0]['statistics']['viewCount'];
                        $('#video_count').text(videoCount);
                        $('#video_span').attr("title","Videos: "+videoCount+"");
                        $('#subscriber_count').text(subscriberCount);
                        $('#subscriber_span').attr("title", "Subscibers: "+subscriberCount+"");
                        $('#view_count').text(viewCount);
                        $('#view_span').attr("title", "View: "+viewCount+"");
                        $('#sub_button').attr("src","https://www.youtube.com/subscribe_embed?usegapi=1&amp;channelid="+video_code+"")
                        $(divAddd).children("#0").children().remove();
                        showPlaylist(upLoadId, 0, 0, "");

                    }
                });
        }

        function getChannelNotEmpty(video_code) {
            $.get('https://www.googleapis.com/youtube/v3/channels?part=statistics,brandingSettings,snippet,contentDetails&id='+video_code+'&key=AIzaSyBeY89QEyaa5z3O1Gtyc4vI6XKBzftsTJE',
                null,
                function (response) {
                    var data = response;
                    var check = data['items'];
                    if(check[0] == null || check[0] == ""){
                        alert("Your Channel is not exist");
                    }
                    else {
//                        var upLoadId = data['items'][0]['contentDetails']['relatedPlaylists']['uploads'];
                        var bannerImageUrl = data['items'][0]['brandingSettings']['image']['bannerImageUrl'];
                        var description = data['items'][0]['brandingSettings']['channel']['description'];
                        var title = data['items'][0]['brandingSettings']['channel']['title'];
                        var profileImageUrl = data['items'][0]['snippet']['thumbnails']['default']['url'];
                        $('#img-profile-channel').attr("src", profileImageUrl);
                        var style = "background-image: url('" + bannerImageUrl + "'); background-size: auto 100% ";
                        var url = "https://www.youtube.com/channel/" + video_code + "";
                        $('#banner').attr("style", style);
                        $('#video_title').attr("value", title);
                        $('#video_description').attr("value", description);
                        $('#title_h1').text(title);
                        $('.link_video').attr("href", url);
                        var des2 = $('#description').text(description);
//                        $('#playlist-input-value-name').attr("value", "Upload Videos");
//                        $('#playlist-input-value').attr("value", "https://www.youtube.com/playlist?list="+upLoadId);
//                        $('#playlist-name').text("Upload Videos");
//                        $('#li_0').children().text("Upload Videos");

//                        var divAddd = document.getElementById('gr_0');
//                        var liSpan = document.getElementById('li_0');
//                        divAddd.classList.add("show-playlist-active");
//                        liSpan.classList.add("show-name-playlist-active");
                        var videoCount = data['items'][0]['statistics']['videoCount'];
                        var subscriberCount = data['items'][0]['statistics']['subscriberCount'];
                        var viewCount = data['items'][0]['statistics']['viewCount'];
                        $('#video_count').text(videoCount);
                        $('#video_span').attr("title","Videos: "+videoCount+"");
                        $('#subscriber_count').text(subscriberCount);
                        $('#subscriber_span').attr("title", "Subscibers: "+subscriberCount+"");
                        $('#view_count').text(viewCount);
                        $('#view_span').attr("title", "View: "+viewCount+"");
                        $('#sub_button').attr("src","https://www.youtube.com/subscribe_embed?usegapi=1&amp;channelid="+video_code+"")
//                        $(divAddd).children("#0").children().remove();
//                        showPlaylist(upLoadId, 0, 0, "");

                    }
                });
        }
        var _countChilGr = 2;
        var _countChilPl = 1;
        var addGroup = document.getElementById('playlist-add-label');
        var divOneVideoPar = document.getElementById('video-playlist');
        var divGroupParent = document.getElementById('playlist-demo-items');
        var htmlGroup =

                '<div class="playlist-toggle-active">' +
                '   <div class="playlist-toggle-trigger" id="playlist-toggle-trigger">' +
                '       <div class="playlist-name" id="playlist-name">name play list</div>' +
                '       <div class="playlist-toggle-name" id ="playlist-toggle-name"></div>' +
                '   </div>' +
                '   <div class="playlist-toggle-content" id="playlist-toggle-content">' +
                '       <div class="i">' +
                '           <div class="playlist-field-name">Group name' +
                '               <span class="playlist-tooltip">' +
                '                   <span id= "playlist-tooltip-trigger" class="playlist-tooltip-trigger">?</span>' +
                '                   <span id = "playlist-tooltip-content" class="playlist-tooltip-content">' +
                '                       <span class="playlist-tooltip-content-inner">' +
                '                           Give a name to your custom video group. It will be displayed in tabs. If you leave it empty, "Untitled" name will be set.' +
                '                       </span>' +
                '                   </span>' +
                '               </span>' +
                '           </div>' +
                '           <div class = "playlist-input-value-names">' +
                '               <input class = "playlist-input-value-name" id="playlist-input-value-name" name="group_name[]" type="text" value="">' +
                '           </div>' +
                '       </div>' +
                '       <div class="playlist-field" id="playlist-field">' +
                '           <div class="playlist-field-name">Sources (playlists)</div>' +
                '           <div class="playlist-item-sources-parent">' +
                '               <div class="playlist-item-sources">' +
                '                   <div class="playlist-item-sources-item" id="playlist-item-sources-item">' +
                '                       <input id= "playlist-input-value" class = "playlist-input-value" name="list_url[][]" placeholder="Add a YouTube source URL" autocomplete="off" type="text" id="playlist-input-value">' +
                '                       <div class="playlist-item-sources-item-remove-icon" id="playlist-item-sources-item-remove-icon" title="Remove this source">x</div>' +
                '           </div></div></div>' +
                '           <div class ="playlist-item-sources-item-add-icon" id ="playlist-item-sources-item-add-icon">+</div>' +
                '       </div>' +
                '       <div class="playlist-item-remove">' +
                '           <span class="playlist-item-remove-icon"></span>' +
                '           <span class="playlist-item-remove-label">Delete group</span>' +
                '</div></div></div>'
            ;

//display tip
        $(document).on("mouseover", ".playlist-tooltip-trigger", function(){
            var tip = $(this).parent().children()[1];
            tip.style.visibility = "visible";
        });
//hidden tip
        $(document).on("mouseout", ".playlist-tooltip-trigger", function(){
            var tip = $(this).parent().children()[1];
            tip.style.visibility = "hidden";
        });
        $(document).on("click", ".watch-video-description-more", function () {
            $(this).parent().children('.watch-video-description')[0].classList.toggle("show-more");
        });

        function addPlGr(countGroup) {
            var divAdddd = document.createElement("div");
            divAdddd.setAttribute("id", "gr_"+countGroup);
            divAdddd.setAttribute("class", "play-list-disactive");
            divOneVideoPar.appendChild(divAdddd);
        }

        addGroup.onclick = function () {
            var id_li = divGroupParent.childElementCount;
            addGroupFunction(id_li);
            addLiName("PlayList Name", id_li);
            var countGroup = divGroupParent.childElementCount-1;
            addPlGr(countGroup);
            i++;
        };
        $(document).on("click",".playlist-item-remove",function () {
            var divParent = $(this).parent().parent().parent();
            var id_li = $(this).parent().parent().parent().index();
            var ul_one_playlist = document.getElementById("nav-playlist");
            $(ul_one_playlist).children("#li_"+id_li+"").remove();
            divParent.remove();
            $(divOneVideoPar).children('#gr_'+id_li+'').remove();
            loadIndexName(ul_one_playlist,"li_");
            loadIndexName(divOneVideoPar,"gr_");
        });
        $(document).on("change", ".playlist-input-value-name", function () {
            var name_list = $(this).val();
            var id_li = $(this).parent().parent().parent().parent().parent().index();
            if(name_list == null||name_list == ""){
                var parent_name = $(this).parent().parent().parent().parent().children(".playlist-toggle-trigger").children(".playlist-name");
                parent_name.text("Playlist Name");
                changeLiName("Playlist Name", id_li);
            }
            if(name_list != ""){
                var parent_name = $(this).parent().parent().parent().parent().children(".playlist-toggle-trigger").children(".playlist-name");
                parent_name.text(name_list);
                changeLiName(name_list,id_li);
            }
        });

        //not empty
        function addGroupFunctionNotEmpty (i, gr_id, gr_name) {
            var divAddGroup = document.createElement('div');
            divAddGroup.setAttribute('class', 'playlist-demo-item');
            divAddGroup.setAttribute('id', 'playlist-demo-item');
            var inputGrID = document.createElement('INPUT');
            inputGrID.setAttribute('name', 'group_id');
            inputGrID.setAttribute('id', 'group_id');
            inputGrID.setAttribute('value', gr_id);
            inputGrID.setAttribute('type', 'hidden');
            divAddGroup.innerHTML = htmlGroup;
            divAddGroup.appendChild(inputGrID);
            $(divAddGroup).children().children('.playlist-toggle-content').children('.i').children('.playlist-input-value-names').children('.playlist-input-value-name').attr("name", "group_name[]");
            $(divAddGroup).children().children('.playlist-toggle-content').children('.i').children('.playlist-input-value-names').children('.playlist-input-value-name').attr("value", gr_name);
            $(divAddGroup).children().children('.playlist-toggle-content').children('.playlist-field').children('.playlist-item-sources-parent').children().children().children('.playlist-input-value').attr("name", "list_url["+i+"][]");
            divGroupParent.appendChild(divAddGroup);
        }
        function addFunctionNotEmpty(divPar, i, li_id, li_url) {
            console.log("this");
            var divv = document.createElement("div");
            divv.setAttribute('class', 'playlist-item-sources');
            var inputLI = document.createElement("input");
            inputLI.setAttribute('name', 'list_id');
            inputLI.setAttribute("value", li_id);
            inputLI.setAttribute("type", "hidden");
            divv.appendChild(inputLI);
            console.log("i");
            console.log(i);
            console.log("li_id");
            console.log(li_id);
            console.log(li_url);
            var divChild1 = document.createElement("div");
            divChild1.setAttribute('class', 'playlist-item-sources-item');
            divChild1.setAttribute('id', 'playlist-item-sources-item');
            divv.appendChild(divChild1);
            var input = document.createElement("input");
            input.setAttribute('class', 'playlist-input-value');
            input.setAttribute('name', 'list_url['+i+'][]');
            input.setAttribute('placeholder', 'Add a YouTube source URL');
            input.setAttribute('autocomplete', 'off');
            input.setAttribute('type', 'text');
            input.setAttribute('id','playlist-input-value');
            input.setAttribute('value', li_url);
            divChild1.appendChild(input);
            var divChild2 = document.createElement("div");
            divChild2.setAttribute('class', 'playlist-item-sources-item-remove-icon');
            divChild2.setAttribute('id', 'playlist-item-sources-item-remove-icon')
            divChild2.setAttribute('title', 'Remove this source');
            var text = document.createTextNode("x");
            divChild2.appendChild(text);
            divChild1.appendChild(divChild2);
//            divPar.appendChild(divv);
            divPar.appendChild(divv);
        }
        function addFunction(divParent, i) {
            var div = document.createElement("div");
            div.setAttribute('class', 'playlist-item-sources');
            var divChild1 = document.createElement("div");
            divChild1.setAttribute('class', 'playlist-item-sources-item');
            divChild1.setAttribute('id', 'playlist-item-sources-item');
            div.appendChild(divChild1);
            var input = document.createElement("input");
            input.setAttribute('class', 'playlist-input-value');
            input.setAttribute('name', 'list_url['+i+'][]');
            input.setAttribute('placeholder', 'Add a YouTube source URL');
            input.setAttribute('autocomplete', 'off');
            input.setAttribute('type', 'text');
            input.setAttribute('id','playlist-input-value');
            divChild1.appendChild(input);
            var divChild2 = document.createElement("div");
            divChild2.setAttribute('class', 'playlist-item-sources-item-remove-icon');
            divChild2.setAttribute('id', 'playlist-item-sources-item-remove-icon');
            divChild2.setAttribute('title', 'Remove this source');
            var text = document.createTextNode("x");
            divChild2.appendChild(text);
            divChild1.appendChild(divChild2);
            divParent.appendChild(div);
        }
        <?php
        if(!empty($groupValue) ){
            $i = 0;
            ?>
            $('#playlist-demo-item').remove();

            <?php
            foreach ($groupValue as $item){
                ?>
                var countGroup = divGroupParent.childElementCount;
                addPlGr(countGroup);

                addGroupFunctionNotEmpty( <?php echo $i?>, <?php echo $item['group_id']?>, '<?php echo $item['group_name'] ?>');
                addLiName('<?php echo $item['group_name']?>', <?php echo $i ?>);
                var divPar = $('[value="<?php echo $item['group_id']?>"][name="group_id"]').parent().children('.playlist-toggle-active').children('.playlist-toggle-content').children('.playlist-field').children('.playlist-item-sources-parent');
                divPar.children().remove();
                <?php
                foreach ($groupListValue[$i] as $key){
                    $listidd = substr($key['list_url'],38);
                    ?>
                    addFunctionNotEmpty(divPar[0], <?php echo $i ?>, <?php echo $key['list_id'] ?>,'<?php echo $key['list_url'] ?>');
                    showPlaylist("<?php echo $listidd ?>", <?php echo $i ?>, 0, "");
                <?php
                }
                    ?>
                <?php
                $i ++;
            }
            ?>
            addClassNameActive(0);
            var gallery_channel_url = $('#gallery_channel_url').val();
            var video_code = gallery_channel_url.replace("https://www.youtube.com/channel/","");
            getChannelNotEmpty(video_code);
            $('#gallery_channel_url').change(function(){
                var gallery_channel_url = $('#gallery_channel_url').val();
                var video_code = gallery_channel_url.replace("https://www.youtube.com/channel/","");
                getChannelNotEmpty(video_code);
            });
            <?php
        }

        else {?>
        addLiName("Playlist Name", 0);

            var countGroup = divGroupParent.childElementCount-1;

            var divAdddd = document.createElement("div");
            divAdddd.setAttribute("id", "gr_"+countGroup);
            divAdddd.setAttribute("class", "play-list-disactive");
            divOneVideoPar.appendChild(divAdddd);
             addPlGr(countGroup);
            var video_url_defaut = $('#gallery_channel_url').val();
            var video_code_defaut = video_url_defaut.replace("https://www.youtube.com/channel/","");
            getChannel(video_code_defaut);
            $('#gallery_channel_url').change(function(){
                var gallery_channel_url = $('#gallery_channel_url').val();
                var video_code = gallery_channel_url.replace("https://www.youtube.com/channel/","");
                getChannel(video_code);
            });
        <?php
        }
        ?>
        //add gr
        function addGroupFunction (i) {
            var divAddGroup = document.createElement('div');
            divAddGroup.setAttribute('class', 'playlist-demo-item');
            divAddGroup.setAttribute('id', 'playlist-demo-item');
            divAddGroup.innerHTML = htmlGroup;
            $(divAddGroup).children().children('.playlist-toggle-content').children('.i').children('.playlist-input-value-names').children('.playlist-input-value-name').attr("name", "group_name[]");
            $(divAddGroup).children().children('.playlist-toggle-content').children('.playlist-field').children('.playlist-item-sources-parent').children().children().children('.playlist-input-value').attr("name", "list_url["+i+"][]")
            divGroupParent.appendChild(divAddGroup);
        }
        function loadIndexName(parent,xx) {
            var countGroup = divGroupParent.childElementCount;

            var i;
            for(i=0;i<countGroup;i++){

                $(parent).children().eq(i).attr("id", xx+i);
            }
        }
        function loadIndexUrl(countUrl,parenUrl) {

            var i;
            for (i = 0; i < countUrl; i++) {

                $(parenUrl).children().eq(i).attr("id", "li_" + i);
            }
        }
        function addLiName(name_list, id_li) {
            $(ul_one_playlist).children("#li_" + id_li + "").remove();
            var li_one_playlist = document.createElement("li");
            li_one_playlist.setAttribute("class", "one-list");
            li_one_playlist.setAttribute("id", "li_" + id_li);
            ul_one_playlist.appendChild(li_one_playlist);
            var span_li = document.createElement("span");
            span_li.setAttribute("style", "padding:10px");
            var span_li_text = document.createTextNode(name_list);
            li_one_playlist.appendChild(span_li);
            span_li.appendChild(span_li_text);
        }

        function changeLiName(name_list, id_li) {
            $(ul_one_playlist).children("#li_" + id_li + "").children().text(name_list);

        }
//change arrow
        $(document).on("click", ".playlist-toggle-trigger", function () {
            var img_arrow = $(this).children(".playlist-toggle-name");
            img_arrow[0].classList.toggle("change-arrow");
            $(this).parent().children(".playlist-toggle-content")[0].classList.toggle("show-div-content");
        });
//close video
        $(document).on("click", ".close", function () {
            $(this).parent()[0].style.display = "none";
            $(this).parent().children(".video-content").children().attr("src", "");
            var divCmtParent = document.getElementById('watch-video-cmts');
            $(divCmtParent).children().remove();

        });
//add playlist
        $(document).on("click", ".playlist-item-sources-item-remove-icon", function () {
            var id_one = $(this).parent().parent().index();
            var id_gr = $(this).parent().parent().parent().parent().parent().parent().parent().index();
            var paUrl = document.getElementById('gr_' + id_gr);
            $(paUrl).children('#' + id_one).remove();
            _countChilPl = divOneVideoPar.childElementCount;
            $(this).parent().parent().remove();
            var countGr = paUrl.childElementCount;
            loadIndexName(paUrl,"");
            $(paUrl).children().eq(countGr - 1).show();
        });
        $(document).on("click", ".playlist-item-sources-item-add-icon", function () {
            var divParent = $(this).parent().children()[1];
            var i = $(this).parent().parent().parent().parent().parent()[0].childElementCount;
//            console.log($(this).parent().parent().parent().parent().parent()[0]);
//            console.log(i);
            addFunction(divParent,i-1);
        });
        function addClassNameActive(id_gr) {
            var divAddd = document.getElementById('gr_' + id_gr + '');
            var countGroup = divGroupParent.childElementCount;
            var liSpan = document.getElementById('li_' + id_gr);
            var i;
            for (i = 0; i < countGroup; i++) {
                $(divOneVideoPar).children().eq(i)[0].classList.remove("show-playlist-active");
                $(ul_one_playlist).children().eq(i)[0].classList.remove("show-name-playlist-active");
            }
            if (divAddd != null) {
                divAddd.classList.add("show-playlist-active");
            }
            liSpan.classList.add("show-name-playlist-active");
        }
        $(document).on("click", ".playlist-input-value", function () {
            var id_gr = $(this).parent().parent().parent().parent().parent().parent().parent().index();

            addClassNameActive(id_gr);
        });
        $(document).on("click", ".playlist-input-value-name", function () {
            var id_gr = $(this).parent().parent().parent().parent().parent().index();
            addClassNameActive(id_gr);
        });
        $(document).on("click", ".one-list", function () {
            var id_gr = $(this).index();
            addClassNameActive(id_gr);
        });
        $(document).on("change", ".playlist-input-value", function () {
            var paGr = $(this).parent().parent().parent().parent().parent().parent().parent();

            var id_gr = $(paGr).index();
            var paOne = $(this).parent().parent();
            var id_one = $(paOne).index();
            var ulLi = document.getElementById('nav-playlist');
            _countChilPl = divOneVideoPar.childElementCount;
            _countChilGr = divGroupParent.childElementCount;
            var i;
            var check = 0;
            for (i = 0; i < _countChilPl; i++) {
                $(divOneVideoPar).children()[i].classList.remove("show-playlist-active");
                if ($(divOneVideoPar).children()[i].getAttribute("id") == "gr_" + id_gr) {
                    check = check + 1;
                }
            }
            if ($(this).val() != "") {

                var paUrl = document.getElementById('gr_' + id_gr);

                var list_url = $(this).val();

                var list_code = list_url.replace("https://www.youtube.com/playlist?list=", "");

                $(paUrl).children('#' + id_one).remove();
                showPlaylist(list_code, id_gr, id_one, "");

                var divAddd = document.getElementById('gr_' + id_gr + '');
                divAddd.classList.add("show-playlist-active");
                var inn;
                var countNext = divAddd.childElementCount;
                for (inn = 0; inn < countNext; inn++) {
                    $(divAddd).children().eq(inn).hide();
                }
            }

        });

    })
</script>
