

<!--<head>-->
<!--    <title>My Uploads</title>-->
<!--<!--    <link rel="stylesheet" type="text/css" href="my_uploads.css">-->-->
<!--</head>-->
<body>
    <div id="login-container" class="pre-auth">
        This application requires access to your YouTube account.
        Please <a href="#" id="login-link">authorize</a> to continue.
    </div>
    <div id="video-container"></div>
    <div class="button-container">
        <button id="prev-button" class="paging-button" onclick="previousPage();">Previous Page</button>
        <button id="next-button" class="paging-button" onclick="nextPage();">Next Page</button>
    </div>
<!--    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>-->
    <script>
        require([
            'jquery',
            'Magenest_YoutubeIntegration/view/web/js/jquery.min',
        ])
    </script>
    <script>
        require([
            'jquery',
            'Magenest_YoutubeIntegration/js/auth',
        ])
    </script>
    <script>
        require([
            'jquery',
            'Magenest_YoutubeIntegration/js/my_uploads',
        ])
    </script>
    <script src_type="url" src="https://apis.google.com/js/client.js?onload=googleApiClientReady">
    //    require([
    //        'jquery',
    //        'Magenest_YoutubeIntegration/js/client',
    //        ''
    //    ])
    </script>
    <span>hihi</span>
</body>

<!-- <span>hihi</span>-->